<?php
if ($currentProduct = $this->getCurrentProduct()) {
  $sku = $currentProduct->getSku();

  $sku_array = array(
                'FIBERS-CA' => 'FIBERS',
                'BBF-ca' => 'BBF',
                '20504231' => 'FHS4B',
                '20080136' => 'TTS',
                '20080131' => 'TSA4C',
                '20080311' => 'OPTE4',
                '20080164' => 'PKIT20010',
                'STR-ca' => 'STR'
            );

            $sku = isset($sku_array[$sku]) ? $sku_array[$sku] : $sku;
}

$array_reviews = $this->getMyCustomRating()->addFieldToFilter('sku', $sku)->addFieldToFilter('type_text', 'reviews')->getData();
// $array_reviews = $this->getMyCustomMethod()->addFieldToFilter('sku', $sku)->addFieldToFilter('type_text', 'reviews')->getData();

$rating = $this->getMyCustomRating()->addFieldToFilter('sku', $sku)->addFieldToFilter('type_text', 'product')->getData();
if (!empty($rating[0]['statistic'])) {
  $statistic = json_decode($rating[0]['statistic'], true);
}
$reviews_sum = 0;
foreach ($statistic['RatingDistribution'] as $value) {
  $reviews_sum += $value['Count'];
}
?>
 <!-- <div data-bv-show="rating_summary" data-bv-ready="true">
  <div class="bv-cleanslate bv-cv2-cleanslate bv_main_container">
    <div class="bv-core-container-103" style="display: flex!important; align-items: center; padding-right: 17px!important">
      <span class="bv-rating-stars-container" style="padding-right: 17px!important;">
        <span class="bv-rating-stars bv-rating-stars-off" aria-hidden="true" style="font-size: 27px!important;"> ★★★★★ </span>
        <span class="bv-rating-stars bv-rating-stars-on bv-width-from-rating-stats-<?php echo round($statistic['AverageOverallRating'], 1) * 20; ?>" aria-hidden="true" style="font-size: 27px!important;"> ★★★★★ </span>
      </span>
      <span class="bv_avgRating_component_container notranslate">
        <button type="button" class="bv_avgRating " aria-expanded="false" aria-label="average rating value is <?php echo round($statistic['AverageOverallRating'], 1); ?> of 5." id="avg-rating-button" role="link" itemprop="ratingValue">
          <?php echo round($statistic['AverageOverallRating'], 1); ?>
        </button>
      </span>
      <div class="bv_numReviews_component_container">
        <meta itemprop="reviewCount" content="<?php echo $reviews_sum; ?>">&nbsp;
        <button type="button" class="bv_numReviews_text " aria-label="Read <?php echo $reviews_sum; ?> Reviews" aria-expanded="false" id="num-reviews-button" role="link">(<?php echo $reviews_sum; ?>)</button>
      </div>
    </div>
    <div class="bv_main_container_row_flex">
      <div class="bv_main_container_row_flex">
        <div class="bv_button_component_container">
          <button type="button" class="bv_button_buttonMinimalist " id="WAR">Write a review </button>
        </div>
      </div>
    </div>

  <div>
        <span style="color: #985234" class="test2"></span>
  </div>

  </div>
</div> 

<div data-bv-show="review_highlights" data-bv-product-id="<?php echo $sku ?>"></div>  -->
<div data-bv-show="rating_summary" data-bv-product-id="<?php echo $sku ?>"></div>

<!-- <script type="text/javascript">
    require([ 'jquery', 'jquery/ui'], function($){
        $(document).ready(function($) {
            $("#WAR").click(function (e) {
                e.preventDefault();
                var id1 = "1";
                var url = "<?php echo $block->getUrl('postjson/page/view', ['_secure' => false]) ?>";
                jQuery.ajax({
                    url: url,
                    type: "POST",
                    data: {
                        id_1:id1
                    },
                    showLoader: true,
                    cache: false,
                    success: function(response){
                        console.log(response);
                        // $(".price").text("$"+response.price);
                        $(".test2").text(response.message);
                        console.log(response);
                    },
                    error:function (res) {
                        console.log(res);
                    }
                });
            })
        });
    });
</script> -->
