<?php
if ($currentProduct = $this->getCurrentProduct()) {
  $sku = $currentProduct->getSku();

  $sku_array = array(
                'FIBERS-CA' => 'FIBERS',
                'BBF-ca' => 'BBF',
                '20504231' => 'FHS4B',
                '20080136' => 'TTS',
                '20080131' => 'TSA4C',
                '20080130' => 'OPTE4',
                '20080164' => 'PKIT20010',
                'STR-ca' => 'STR'
            );

            $sku = isset($sku_array[$sku]) ? $sku_array[$sku] : $sku;
}

$array_reviews = $this->getMyCustomRating()->addFieldToFilter('sku', $sku)->addFieldToFilter('type_text', 'reviews')->getData();

$rating = $this->getMyCustomRating()->addFieldToFilter('sku', $sku)->addFieldToFilter('type_text', 'product')->getData();
if (!empty($rating[0]['statistic'])) {
  $statistic = json_decode($rating[0]['statistic'], true);
}
$reviews_sum = 0;
foreach ($statistic['RatingDistribution'] as $value) {
  $reviews_sum += $value['Count'];
}
?>

<div data-bv-show="rating_summary" data-bv-product-id="<?php echo  $sku ?>"></div>
<div data-bv-show="review_highlights" data-bv-product-id="<?php echo $sku ?>"></div>

<script type="text/javascript">
    require([ 'jquery', 'jquery/ui'], function($){
        $(document).ready(function($) {
            var sku = <?php echo json_encode($sku); ?>;
            var typeJson = "submitquestion.json";
            var pattern = /^[a-z0-9_-]+@[a-z0-9-]+\.([a-z]{1,6}\.)?[a-z]{2,6}$/i;
            $("#bv-search-results-review__question-button").click(function (e) {
                if ($("#bv-textarea-review-search-field-questionsummary").val() === '' || $("#bv-textarea-review-search-field-questionsummary").val().length > 255 ){
                    $('.bv-fieldset-questionsummary').addClass('bv-error');
                    $('.bv-fieldset-questionsummary').removeClass('bv-valid');
                    return;
                }
                else {
                    $('.bv-fieldset-questionsummary').addClass('bv-valid');
                    $('.bv-fieldset-questionsummary').removeClass('bv-error');
                }
                if($("#bv-text-revies-search-field-usernickname").val() === ''){
                    $('.bv-fieldset-usernickname').addClass('bv-error');
                    $('.bv-fieldset-usernickname').removeClass('bv-valid');
                    return;
                }
                else {
                    $('.bv-fieldset-usernickname').addClass('bv-valid');
                    $('.bv-fieldset-usernickname').removeClass('bv-error');
                }
                if($("#bv-email-field-review-search-hostedauthentication_authenticationemail").val() === ''  || $("#bv-email-field-review-search-hostedauthentication_authenticationemail").val().search(pattern) !== 0){
                    $('.bv-fieldset-hostedauthentication_authenticationemail').addClass('bv-error');
                    $('.bv-fieldset-hostedauthentication_authenticationemail').removeClass('bv-valid');
                    return;
                }
                else {
                    $('.bv-fieldset-hostedauthentication_authenticationemail').addClass('bv-valid');
                    $('.bv-fieldset-hostedauthentication_authenticationemail').removeClass('bv-error');
                    e.preventDefault();
                    var comment = $("#bv-textarea-review-search-field-questionsummary").val();
                    var nickname = $("#bv-text-revies-search-field-usernickname").val();
                    var location = $("#bv-text-review-search-field-userlocation").val();
                    var email = $("#bv-email-field-review-search-hostedauthentication_authenticationemail").val();
                    console.log(comment);
                    console.log(nickname);
                    console.log(location);
                    console.log(email);
                    console.log(sku);
                    var url = "<?php echo $block->getUrl('postjson/page/view', ['_secure' => false]) ?>";
                    // jQuery.ajax({
                    //     url: url,
                    //     type: "POST",
                    //     data: {
                    //         comment:comment,
                    //         nickname:nickname,
                    //         location:location,
                    //         email:email,
                    //         sku:sku,
                    //         typeJson:typeJson
                    //     },
                    //     showLoader: true,
                    //     cache: false,
                    //     success: function(response){
                    //         console.log(response);
                    //     },
                    //     error:function (res) {
                    //         console.log(res);
                    //     }
                    // });
                }
            });

            $("#bv-search-results-question__question-button").click(function (e) {
                if ($("#bv-textarea-question-search-field-questionsummary").val() === '' || $("#bv-textarea-question-search-field-questionsummary").val().length > 255 ){
                    $('.bv-fieldset-questionsummary').addClass('bv-error');
                    $('.bv-fieldset-questionsummary').removeClass('bv-valid');
                    return;
                }
                else {
                    $('.bv-fieldset-questionsummary').addClass('bv-valid');
                    $('.bv-fieldset-questionsummary').removeClass('bv-error');
                }
                if($("#bv-text-question-search-field-usernickname").val() === ''){
                    $('.bv-fieldset-usernickname').addClass('bv-error');
                    $('.bv-fieldset-usernickname').removeClass('bv-valid');
                    return;
                }
                else {
                    $('.bv-fieldset-usernickname').addClass('bv-valid');
                    $('.bv-fieldset-usernickname').removeClass('bv-error');
                }
                if($("#bv-email-question-search-field-hostedauthentication_authenticationemail").val() === ''  || $("#bv-email-question-search-field-hostedauthentication_authenticationemail").val().search(pattern) !== 0){
                    $('.bv-fieldset-hostedauthentication_authenticationemail').addClass('bv-error');
                    $('.bv-fieldset-hostedauthentication_authenticationemail').removeClass('bv-valid');
                    return;
                }
                else {
                    $('.bv-fieldset-hostedauthentication_authenticationemail').addClass('bv-valid');
                    $('.bv-fieldset-hostedauthentication_authenticationemail').removeClass('bv-error');
                    e.preventDefault();
                    var comment = $("#bv-textarea-question-search-field-questionsummary").val();
                    var nickname = $("#bv-text-question-search-field-usernickname").val();
                    var location = $("#bv-text-question-search-field-userlocation").val();
                    var email = $("#bv-email-question-search-field-hostedauthentication_authenticationemail").val();
                    console.log(comment);
                    console.log(nickname);
                    console.log(location);
                    console.log(email);
                    console.log(sku);
                    var url = "<?php echo $block->getUrl('postjson/page/view', ['_secure' => false]) ?>";
                    // jQuery.ajax({
                    //     url: url,
                    //     type: "POST",
                    //     data: {
                    //         comment:comment,
                    //         nickname:nickname,
                    //         location:location,
                    //         email:email,
                    //         sku:sku,
                    //         typeJson:typeJson
                    //     },
                    //     showLoader: true,
                    //     cache: false,
                    //     success: function(response){
                    //         console.log(response);
                    //     },
                    //     error:function (res) {
                    //         console.log(res);
                    //     }
                    // });
                }
            });
        });
    });
</script>